uranai_list = [
"多分いい日",
"やばいいい日　ガチで",    
"天　滅　鬼　鎮　魂　呶　夢",
"鎮魂！　鎮魂！　鎮魂！　鎮魂！　万光ー",
"大奇知",
"大吉",
"吉",
"馬券買え",
"とりま競馬",
"宝くじ買え",
"大根",
"いい日！多分ね！",
"今日は部屋籠ろ！",
"酒の日",
"Present day, Present time  Ahahahaha",
"少々吉",
"うまぴょい",
"ツイてる",
"新しい事始めるといいかも",
"今日は貯金の日！",
"ウルトイン",
"レベル２トップギャンク",
"ベセスダの日",
"エオルゼア行こう",
"楽器の日！いろいろ練習しよ！",
"音楽の日！いろいろ聴こう！",
"調べものの日！気になるやつ調べよ！",
"プログラミングの日！書け",
"モザンピークヒア",
"龍角散",
"恋愛運MAX 告れ",
"真の大吉　おめでとう",
"唯一のハズレ　どんまい",
"カラオケの日！　楽しんじゃお！",
"草",
"竹",
"森",
"おしゃれの日",
"筋トレの日！メニューを考えてがんばろか！",
"２回目の青バフをミッドのヤスオにとられる日　ｇｇ",
"top トリン　mid　ヤスオ　jg  マスイ　bot  ヴェイン　sup　ブランド　gg",
"topにレベル１からギャンクしてテレポ明けにもう一回ギャンクに入ってるのに一度もカバー入れないＪＧ引く日 gg ",
"マンガの日　漫画漁りしよ～",
"スカイプでみんなでゲームしてた日を思い出す日",
"初めてやったゲームを思い出す日",
"ＭＭＯでの経験を思い出す日",
"出航",
"人生最大のやらかしを思い出す日",
"後悔を思い返す日",
"休みの日",
"お昼寝の日"
]

[config]
<<<<<<< HEAD
token = "ODMxMzU1MDAyMDE0NTMxNjI1.YHUBrg.VDAaN0q6JhTOkoBBhmhvLXyIIps"
channel_id = 831420404286881827
=======
token = "ODMxMzU1MDAyMDE0NTMxNjI1.YHUBrg.EqxrGBTuCH17vs0XYKROsSPwChM"
channel_id = テストしたいチャンネルのid
>>>>>>> 31103673f45f817e609c4be930155e8bd810ac3a


